# Generated by Django 4.1.7 on 2023-03-30 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Please enter the quantity in Kgs from 100kg to 10 tonnes', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('price', models.PositiveIntegerField(help_text='Please enter the price per kg of the product you are trying to sell!', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('description', models.CharField(blank=True, help_text='Describe your product shortly', max_length=250)),
                ('user_product_table', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
