# Generated by Django 4.1.7 on 2023-03-30 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('government_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(help_text='Street or village', max_length=80)),
                ('mobile_number', models.CharField(max_length=15)),
                ('secret_key', models.CharField(default='.321ytrewq', help_text='enter your 8 digit/character key given', max_length=100)),
                ('comments', models.CharField(default='', max_length=320)),
                ('status', models.CharField(choices=[('INSPECTED', 'inspected'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product_inspected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.products')),
            ],
            options={
                'verbose_name': 'inspectors',
            },
        ),
    ]
