# Generated by Django 4.1.7 on 2023-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='is_registered',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=4),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='secret_key',
            field=models.CharField(default='321ytrewq', help_text='enter your 8 digit/character key given', max_length=100),
        ),
    ]
