# Generated by Django 4.1.7 on 2023-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_api', '0001_initial'),
        ('inspector_api', '0003_alter_inspector_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorProductRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.CharField(default='', max_length=320)),
                ('status', models.CharField(choices=[('INSPECTED', 'inspected'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('inspector_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_inspected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.products')),
            ],
            options={
                'verbose_name': 'inspector_product_relation_table',
            },
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
    ]
