# Generated by Django 4.1.7 on 2023-04-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector_api', '0005_rename_inspector_name_inspectorproductrelation_inspector_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectorproductrelation',
            old_name='inspector_id',
            new_name='inspector',
        ),
        migrations.RenameField(
            model_name='inspectorproductrelation',
            old_name='product_inspected_id',
            new_name='product_inspected',
        ),
    ]
