# Generated by Django 4.1.7 on 2023-03-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], default='FARMER', max_length=10),
        ),
    ]
