# Generated by Django 4.1.7 on 2023-04-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('INSPECTOR', 'Inspector')], default='FARMER', max_length=10),
        ),
    ]
