# Generated by Django 4.1.7 on 2023-03-24 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('government_id', models.CharField(max_length=50, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer')], default='FARMER', max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('device_used', models.CharField(default='Desktop-Windows_11', max_length=30)),
                ('country', models.CharField(choices=[('TZ', 'Tanzania'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('MW', 'Malawi')], default='TZ', max_length=4)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(help_text='Street or village', max_length=80)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
