name: Pycodestyle linter

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pip upgrade
    - run: python -m pip install --upgrade pip
    - name: requirements installation in django
    - run: pip install -r requirements.txt
    - name: checking django server if it has no error
    - run: python manage.py runserver
    - name: pycodestyle check and download
    - run: pip install pycodestyle ; pycodestyle *.py
    
