name: Django checker

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout v3
        uses: actions/checkout@v3
        
      - name: Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }} -pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
    
      - name: pip upgrade
        run: python -m pip install --upgrade pip
      
      - name: requirements installation in django
        run: pip install -r requirements.txt
      
      - name: pycodestyle check and download
        run: |
          pip install pycodestyle
          pycodestyle --statistics .
      
      - name: run Migrations
        run: python manage.py migrate --database=default
      - name: checking django server if it has no error
        run: python manage.py runserver --noreload --timeout 300
